### ISSUE TITLE
Thank you for this!

### ISSUE THREAD

**Issue by ankile** [jacobwatkins1/Nielsen-and-Chuang-Solutions#1]
This is a very nice writeups of many problems that are super helpful when reading for a QC exam, thank you!

(This is obviously not the best avenue for such feedback, but didn't anywhere else..)

**Comment by jacobwatkins1** [comment]
My pleasure Lars, I'm very appreciative that you sent this so I can see that someone benefited from these!

Is there any way that these solutions and guided answers could be made more valuable to you?

Best of luck on your exam! -Jacob
________________________________
From: Lars Lien Ankile ***@***.***>
Sent: Wednesday, December 14, 2022 16:29
To: jacobwatkins1/Nielsen-and-Chuang-Solutions ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jacobwatkins1/Nielsen-and-Chuang-Solutions] Thank you for this! (Issue #1)


This is a very nice writeups of many problems that are super helpful when reading for a QC exam, thank you!

(This is obviously not the best avenue for such feedback, but didn't anywhere else..)

**Comment by ankile** [comment]
My pleasure; I think it's important to show appreciation when one can—I'm sure many more people than those who reach out find some value from projects like this!

Regarding what could make it more valuable, I think the most important is probably coverage/completeness. It's always a bummer to find a good resource but realize they lack a solution to just the problem you're stuck on.

E.g., there's a gap in the solutions in ch. 10 I'd love to have as I'm working my way through error-correcting codes now.

Hope this helps—and keep it up! 😊

**Comment by jacobwatkins1** [comment]
That's great feedback, thank you! I took a detour from Ch 10 to do as much of Ch 2 as possible, but maybe this will inspire me to return to it. :) Good luck with your learning!
________________________________
